
import { Geist, Geist_Mono } from "next/font/google";


import Protected from "@/app/app-wrapper/Protected";
import Provider from "../app-wrapper/provider";

import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

import MainContent from "./mainContent";
import NextTopLoader from "nextjs-toploader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pharmart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
 
      <div className="w-screen h-screen">
           
              
      <Protected>
        
          <Provider>
          
          <Header />
         
          <MainContent>
            {children}
          </MainContent>

          <Footer />
          
          
            </Provider>
         </Protected>
   
      </div>
    
  );
}
